export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const PROJECTS_LOADED = 'PROJECTS_LOADED';
export const PROJECT_LOAD_FAILED = 'PROJECT_LOAD_FAILED';
export const SET_CURRENT_PROJECT = 'SET_CURRENT_PROJECT';

export const TICKETS_LOADED = 'TICKETS_LOADED';
export const TICKETS_LOAD_FAILED = 'TICKETS_LOAD_FAILED';
export const TICKET_UPDATED = 'TICKET_UPDATED';
export const TICKET_UPDATE_FAILED = 'TICKET_UPDATE_FAILED';
